Config        = {}
Config.Lang   = 'fr'
Config.esx    = true --Turn this true if you are using esx


Config.TextFr = {
	start         = "La BanList et l'historique a ete charger avec succes",
	starterror    = "ERROR : La BanList ou l'historique n'a pas ete charger nouvelle tentative.",
	banlistloaded = "La BanList a ete charger avec succes.",
	historyloaded = "La BanListHistory a ete charger avec succes.",
	loaderror     = "ERROR : La BanList n a pas été charger.",
	add           = "Veillez entrer /ban:add (ID) (Durée en jours) (Raison)",
	addoff        = "Veillez entrer /ban:addoff (Durée en jours) (Nom steam)",
	addhistory    = "Veillez entrer /ban:history 0 (Steam name)",
	forcontinu    = " jours. Pour continuer entrer /ban:reason (Raison du ban)",
	noreason      = "Raison Inconnue",
	during        = " pendant : ",
	noresult      = "Il n'y a pas autant de résultats !",
	isban         = " a été déban",
	invalidid     = "ID du joueur incorrect",
	invalidname   = "Le nom n'est pas valide",
	invalidtime   = "Duree du ban incorrecte",
	yourban       = "Vous avez ete ban pour : ",
	yourpermban   = "Vous avez ete ban permanant pour : ",
	youban        = "Vous avez banni : ",
	forr          = " jours. Pour : ",
	permban       = " de facon permanente parce que ",
	timeleft      = ". Il reste : ",
	day           = " Jours ",
	hour          = " Heures ",
	minute        = " Minutes ",
}


Config.TextEn = {
	start         = "The BanList and history has been loaded successfully.",
	starterror    = "ERROR: The BanList and history has not been loaded new try.",
	banlistloaded = "The BanList has been loaded successfully.",
	historyloaded = "The BanListHistory has been loaded successfully.",
	loaderror     = "ERROR: The BanList was not loaded.",
	add           = "Please enter /ban:add (ID) (Duration in days) (Ban reason)",
	addoff        = "Please enter /ban:addoff (Duration in days) (Steam name)",
	addhistory    = "Please enter /ban:history 0 (Steam name)",
	forcontinu    = " days. To continue entering /ban:reason (Ban reason)",
	noreason      = "unknown reason",
	during        = " during : ",
	noresult      = "There are not as many results!",
	isban         = " was unban",
	invalidid     = "Player ID incorrect",
	invalidname   = "The name is not valid",
	invalidtime   = "Bad ban duration",
	yourban       = "You have been ban for : ",
	yourpermban   = "You have been ban permanent for : ",
	youban        = "You have ban : ",
	forr          = " days. For : ",
	permban       = " permanently for ",
	timeleft      = ". Time remains : ",
	day           = " Days ",
	hour          = " Hours ",
	minute        = " Minutes ",
}